import json
import boto3
import os
import urllib.parse
from datetime import datetime

# Initialize AWS clients
s3_client = boto3.client('s3')
bedrock_agent_runtime_client = boto3.client('bedrock-agent-runtime')

# Get agent details from environment variables
REPO_INTELLIGENCE_AGENT_ID = os.environ.get("REPO_INTELLIGENCE_AGENT_ID")
REPO_INTELLIGENCE_AGENT_ALIAS_ID = os.environ.get("REPO_INTELLIGENCE_AGENT_ALIAS_ID")
TECHNOLOGY_ASSESSMENT_AGENT_ID = os.environ.get("TECHNOLOGY_ASSESSMENT_AGENT_ID")
TECHNOLOGY_ASSESSMENT_AGENT_ALIAS_ID = os.environ.get("TECHNOLOGY_ASSESSMENT_AGENT_ALIAS_ID")
MATURITY_ASSESSMENT_AGENT_ID = os.environ.get("MATURITY_ASSESSMENT_AGENT_ID")
MATURITY_ASSESSMENT_AGENT_ALIAS_ID = os.environ.get("MATURITY_ASSESSMENT_AGENT_ALIAS_ID")
INTEGRATION_RECOMMENDATIONS_AGENT_ID = os.environ.get("INTEGRATION_RECOMMENDATIONS_AGENT_ID")
INTEGRATION_RECOMMENDATIONS_AGENT_ALIAS_ID = os.environ.get("INTEGRATION_RECOMMENDATIONS_AGENT_ALIAS_ID")
OUTPUT_BUCKET = os.environ.get("OUTPUT_BUCKET")

print(f"[DEBUG] OUTPUT_BUCKET = {OUTPUT_BUCKET}")


def invoke_agent_helper(agent_id, alias_id, session_id, input_text):
    """Invoke a Bedrock agent and return the complete response."""
    print(f"[DEBUG] Invoking agent {agent_id}")
    try:
        response = bedrock_agent_runtime_client.invoke_agent(
            agentId=agent_id,
            agentAliasId=alias_id,
            sessionId=session_id,
            inputText=input_text
        )

        completion = ""
        for event in response.get("completion"):
            chunk = event["chunk"]
            completion += chunk["bytes"].decode()

        print(f"[DEBUG] Agent {agent_id} completed successfully")
        return completion
    except Exception as e:
        print(f"[ERROR] Agent {agent_id} failed: {e}")
        return f"Error generating this section: {e}"


def assemble_intelligence_report(repo_name, scan_date, intelligence_data,
                                  technology_assessment, maturity_assessment,
                                  integration_recommendations):
    """Assemble the final Data Intelligence Report in Markdown format."""

    # Parse the intelligence data for the executive summary
    try:
        intel = json.loads(intelligence_data) if isinstance(intelligence_data, str) else intelligence_data
        total_files = intel.get('total_file_count', 'Unknown')
        maturity_score = intel.get('project_maturity_score', 'Unknown')
        maturity_out_of = intel.get('maturity_out_of', 5)
        has_cicd = intel.get('has_ci_cd_pipeline', False)
        has_tests = intel.get('has_tests', False)
        detected_tech = intel.get('detected_de_technologies', [])
        repo_url = intel.get('repo_url', '')
    except Exception:
        total_files = 'Unknown'
        maturity_score = 'Unknown'
        maturity_out_of = 5
        has_cicd = False
        has_tests = False
        detected_tech = []
        repo_url = ''

    cicd_status = "Present" if has_cicd else "Not detected"
    test_status = "Present" if has_tests else "Not detected"
    tech_list = ", ".join(detected_tech) if detected_tech else "None detected"

    report = f"""# Data Intelligence Report: {repo_name}

**Generated:** {scan_date}
**Repository:** {repo_url}
**Report Type:** Automated Data Engineering Assessment

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Files | {total_files} |
| Maturity Score | {maturity_score}/{maturity_out_of} |
| CI/CD Pipeline | {cicd_status} |
| Test Coverage | {test_status} |
| DE Technologies | {tech_list} |

---

{technology_assessment}

---

{maturity_assessment}

---

{integration_recommendations}

---

*This report was automatically generated by the Data Intelligence Platform.*
*Powered by Amazon Bedrock and AWS Lambda.*
"""
    return report


def handler(event, context):
    """Main Lambda handler for the intelligence report orchestrator."""
    print(f"[DEBUG] Intelligence Orchestrator started")
    print(f"[DEBUG] Event: {json.dumps(event)}")

    # 1. Get the repo URL from the S3 event trigger
    bucket = event['Records'][0]['s3']['bucket']['name']
    key = urllib.parse.unquote_plus(
        event['Records'][0]['s3']['object']['key']
    )

    # Decode the filename back into a GitHub URL
    filename = key.replace('intelligence-inputs/', '')
    repo_url = filename.replace('---', '://', 1)
    parts = repo_url.split('://', 1)
    if len(parts) == 2:
        domain_and_path = parts[1]
        domain_and_path = domain_and_path.replace('-', '/', 2)
        repo_url = parts[0] + '://' + domain_and_path

    session_id = context.aws_request_id
    scan_date = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')
    report_date = datetime.utcnow().strftime('%Y-%m-%d')

    print(f"[DEBUG] Repo URL: {repo_url}")
    print(f"[DEBUG] Session ID: {session_id}")

    # 2. Extract repo name for the output path
    repo_name = repo_url.split('/')[-1].replace('.git', '')
    output_key = f"intelligence-reports/{report_date}/{repo_name}/intelligence_report.md"

    print(f"[DEBUG] Repo name: {repo_name}")
    print(f"[DEBUG] Output key: {output_key}")

    # 3. Step 1 of chain: Call the intelligence scanner agent
    print("[DEBUG] Step 1: Calling intelligence scanner agent...")
    intelligence_json = invoke_agent_helper(
        REPO_INTELLIGENCE_AGENT_ID,
        REPO_INTELLIGENCE_AGENT_ALIAS_ID,
        session_id,
        repo_url
    )

    # 4. Steps 2-4 of chain: Call all three analytical agents with the
    # intelligence JSON
    print("[DEBUG] Step 2: Calling technology assessment agent...")
    technology_assessment = invoke_agent_helper(
        TECHNOLOGY_ASSESSMENT_AGENT_ID,
        TECHNOLOGY_ASSESSMENT_AGENT_ALIAS_ID,
        f"{session_id}-tech",
        intelligence_json
    )

    print("[DEBUG] Step 3: Calling maturity assessment agent...")
    maturity_assessment = invoke_agent_helper(
        MATURITY_ASSESSMENT_AGENT_ID,
        MATURITY_ASSESSMENT_AGENT_ALIAS_ID,
        f"{session_id}-maturity",
        intelligence_json
    )

    print("[DEBUG] Step 4: Calling integration recommendations agent...")
    integration_recommendations = invoke_agent_helper(
        INTEGRATION_RECOMMENDATIONS_AGENT_ID,
        INTEGRATION_RECOMMENDATIONS_AGENT_ALIAS_ID,
        f"{session_id}-integration",
        intelligence_json
    )

    # 5. Parse intelligence data for the executive summary table
    try:
        intel_data = json.loads(intelligence_json.split('{', 1)[1].rsplit('}', 1)[0].join(['{', '}']))
    except Exception:
        intel_data = intelligence_json

    # 6. Assemble the complete report in Python
    print("[DEBUG] Step 5: Assembling final report...")
    report_content = assemble_intelligence_report(
        repo_name=repo_name,
        scan_date=scan_date,
        intelligence_data=intel_data,
        technology_assessment=technology_assessment,
        maturity_assessment=maturity_assessment,
        integration_recommendations=integration_recommendations
    )

    # 7. Save the report to S3 with date-based path
    try:
        print(f"[DEBUG] Saving report to {OUTPUT_BUCKET}/{output_key}")
        s3_client.put_object(
            Bucket=OUTPUT_BUCKET,
            Key=output_key,
            Body=report_content,
            ContentType='text/markdown'
        )
        print(f"[DEBUG] Report saved successfully")
    except Exception as e:
        print(f"[ERROR] Failed to save report: {e}")
        raise e

    return {
        'statusCode': 200,
        'body': json.dumps({
            'message': 'Intelligence report generated successfully',
            'report_location': f"s3://{OUTPUT_BUCKET}/{output_key}",
            'repo_name': repo_name,
            'scan_date': scan_date
        })
    }